public class MinhaClasse {
    public static void main(String[] args) {
        System.out.println("EU AMO A GIOVANNA RUZON HINGST GIRASOLE, ELA É O AMOR DA MINHA VIDA EU VOU ME CASAR COM ELA E TER FILHOS LINDOS E VIVEREMOS JUNTOS PELO RESTO DOS TEMPOS PORQUÊ EU AMO MUITO MUTO MUITO MUITO ELA");
    }
}